import { challengesType } from "../types/insurance.types";

export const newChallenges: challengesType[] = [
  {
    challengesId: "", // Automatically generated by generateUID()
    name: "Challenge 1",
    description: "Description of Challenge 1",
    challenge: "Complete task 1",
    tokenPrize: "10",
    claimedUsers: [],
    createdAt: "",
  },
  {
    challengesId: "", // Automatically generated by generateUID()
    name: "Challenge 2",
    description: "Description of Challenge 2",
    challenge: "Complete task 2",
    tokenPrize: "20",
    claimedUsers: [],
    createdAt: "",
  },
];
